---
- hosts: localhost
  gather_facts: false
  roles:
    - role: common
      tags: common
    - role: install_pyenv
      tags: install_pyenv
    - role: install_google_cloud_sdk
      tags: install_google_cloud_sdk
    - role: install_chrome
      tags: install_chrome
  # tasks:
  #   # - include_tasks: tasks/dotfiles.yaml
