---
- name: Execute environment construction
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Execute tasks that require root privileges
      ansible.builtin.import_tasks:
        file: tasks/system.yaml
      become: true

    - name: Execute task
      ansible.builtin.import_tasks:
        file: tasks/user_taks.yaml
  handlers:
    - name: User level handlers
      ansible.builtin.import_tasks:
        file: tasks/user_handlers.yaml
