---
- block:
  - name: install common packages
    apt:
      name:
        - zip
        - unzip
        - ffmpeg
        - poppler-utils
      state: latest

  - name: install python build dependencies
    apt:
      name:
        - build-essential
        - libssl-dev
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - curl
        - libncursesw5-dev
        - xz-utils
        - tk-dev
        - libxml2-dev
        - libxmlsec1-dev
        - libffi-dev
        - liblzma-dev
      state: latest

  - name: install poetry build dependencies
    apt:
      name:
        - python3-distutils
      state: latest

  become: yes
