---
- name: Disable ctrl+s and ctrl+q
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    create: true
    insertafter: EOF
    marker: "# {mark} ANSIBLE disable ctrl+s and ctrl+q"
    block: |
      if [[ -t 0 ]]; then
        stty stop undef
        stty start undef
      fi
    mode: "0644"

- name: Add integration with 1password
  ansible.builtin.blockinfile:
    path: ~/.bash_aliases
    create: true
    insertafter: EOF
    marker: "# {mark} ANSIBLE integration with 1password"
    block: "{{ item }}"
  with_file:
    - block_files/part_bash_aliases.sh

# install pyenv
- name: Clone pyenv repository
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.pyenv
    version: v20160726
  notify:
    - configure_pyenv

- name: Add pyenv startup commands
  ansible.builtin.include_tasks: tasks/user_configure_pyenv.yaml
  loop:
    - ~/.bashrc
    - ~/.profile
    - ~/.bash_profile
    - ~/.bash_login
  loop_control:
    loop_var: startup_file_path

- name: Fetch poetry installer
  ansible.builtin.uri:
    url: https://install.python-poetry.org
    return_content: true
  register: poetry_installer
  notify:
    - run_poetry_installer

- name: Run poetry installer
  ansible.builtin.command:
    cmd: python3
    stdin: "{{ poetry_installer.content }}"
    creates: ~/.local/bin/poetry
  listen:
    - run_poetry_installer

- name: Start the handler after downloading the installer for poetry
  ansible.builtin.meta: flush_handlers

- name: Check poetry config virtualenvs.in-project
  ansible.builtin.command:
    cmd: ~/.local/bin/poetry config virtualenvs.in-project
  register: virtualenvs_in_project
  changed_when: false

- name: Set virtualenvs.in-project to true
  ansible.builtin.command:
    cmd: ~/.local/bin/poetry config virtualenvs.in-project true
  when: virtualenvs_in_project.stdout.lower() != "true"
  register: result_cmd
  changed_when: result_cmd.rc == 0
