---
- name: Configure pyenv
  ansible.builtin.command:
    cmd: ./configure
    chdir: ~/.pyenv/src
  register: result_cmd
  changed_when: result_cmd.rc == 0
  notify:
    - make_pyenv
  listen:
    - configure_pyenv

- name: Make pyenv
  community.general.make:
    chdir: ~/.pyenv/src
  listen:
    - make_pyenv

- name: Run poetry installer
  ansible.builtin.command:
    cmd: python3
    stdin: "{{ poetry_installer.content }}"
    creates: ~/.local/bin/poetry
  listen:
    - run_poetry_installer
