---
- name: Add startup commands to ~/.profile.
  blockinfile:
    path: ~/.profile
    create: yes
    insertafter: EOF
    marker: "# {mark} ANSIBLE ssh-agent startup command."
    block: "{{item}}"
  with_file:
    - files/enable_ssh_agent.sh
