---
- name: Check .ssh directory
  stat:
    path: "{{ssh_dir_path}}"
  register: ssh_dir

- name: Create symbolic link ~/.ssh directory
  file:
    src: "{{ssh_dir_path}}"
    dest: ~/.ssh
    state: link
  when: ssh_dir.stat.exists == true
