---
- name: Disable Ctrl+S and Ctrl+Q.
  blockinfile:
    path: ~/.bashrc
    create: yes
    insertafter: EOF
    marker: "# {mark} ANSIBLE Disable Ctrl+S and Ctrl+Q."
    block: |
      if [[ -t 0 ]]; then
        stty stop undef
        stty start undef
      fi
