- name: Install packages
  apt:
    name:
      # Tools
      - zip
      - unzip
      - ffmpeg
      - poppler-utils
      - openssh-client
      # VS Code required
      - socat
    state: latest
  become: true
