- name: Install packages
  apt:
    name:
      # Tools
      - zip
      - unzip
      - ffmpeg
      - poppler-utils
      - openssh-client
      # VS Code required
      - socat
      # install_google_cloud_sdk and install_chrome
      - gpg
    state: latest
  become: true
