- name: Install packages
  apt:
    name:
      # Tools
      - zip
      - unzip
      - ffmpeg
      - poppler-utils
      - openssh-client
      # VS Code required
      - socat
      # install_google_cloud_sdk and install_chrome
      - gpg
      # pyenv
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    state: latest
  become: yes
