---
- name: Import public key
  ansible.builtin.apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    keyring: /usr/share/keyrings/chrome.google.gpg
    state: present
  become: yes

- name: Add the Google Chrome distribution URI as a package source
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/chrome.google.gpg] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    state: present
  become: yes
