---
- name: Fetch poetry
  ansible.builtin.uri:
    url: https://install.python-poetry.org
    return_content: yes
  register: poetry_installer

- name: Run poetry installer
  ansible.builtin.command:
    cmd: python3
    stdin: "{{ poetry_installer.content }}"
    creates: ~/.local/bin/poetry
  